name: pointo
description: A new Flutter project.

publish_to: 'none' 

version: 1.2.5+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4
  intl_phone_field: ^3.2.0
  chewie: ^1.7.0
  video_player: ^2.7.2
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.0
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  provider: ^6.0.0
  rxdart: ^0.27.7
  flutter_launcher_icons: ^0.13.1
  intl: ^0.20.2
  implicitly_animated_list: ^2.3.0
  # implicitly_animated_reorderable_list:
  #    path: /Users/d_kamkov/Documents/Workspace/dkamkov_app/lib/packages/implicitly_animated_reorderable_list-0.4.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_reorderable_list: ^1.3.1
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  drag_and_drop_lists: ^0.4.2
  universal_platform: ^1.1.0
  # implicitly_animated_reorderable_list: ^0.4.2

dependency_overrides:
  app_links: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

    - assets/icon/dmitry.jpg

    - assets/icon/skating.jpg
    - assets/icon/football.jpg
    - assets/icon/snowboard.jpg
    - assets/icon/wakeboard.jpg

    - assets/video/skating.mp4
    - assets/video/football.mp4
    - assets/video/snowboard.mp4
    - assets/video/wakeboard.mp4
    

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_img.jpg"